const Mock = require('mockjs');

function randomSuccess() {
  return Mock.mock({
    result: {},
    'success|1': true,
    error: '错误信息',
  });
}
module.exports = {
  '/api/loan/product/channel': function () {
    return Mock.mock({
      "success": true,
      "result": {
        "total": 3,
        "data": [{
          "id": 43,
          "businessCategory": 1,
          "category": 1,
          "types": 1,
          "channelRO": null,
          "process": 1,
          "name": "20190313无颜测试",
          "code": "20190313000001",
          "num": "20190313000001",
          "subtitle": "20190313无颜测试副",
          "note": "测试",
          "problem": "测试",
          "repayment": null,
          "repaymentCycle": null,
          "repaymentDay": 25,
          "modelHead": 1,
          "modelYear": 2,
          "overdue": null,
          "defaultRepayment": null,
          "creditLeft": 0,
          "creditRight": 1000000,
          "applyLimit": 5,
          "status": 1,
          "basisId": null,
          "description": "20190313无颜测试",
          "productCondition": null,
          "productProtocol": null,
          "productRateList": null,
          "productTollList": null,
          "banner": null,
          "productShow": ["政采云云智贷"],
          "updator": 10007000000,
          "updateTime": 1552463243000,
          "smallImage": null,
          "bigImage": null,
          "statistics": null,
          "loop": true,
          "channelName": "中国农业银行股份有限公司浙江省分行",
          "channelId": 1,
          "channelCode": "ABC330106001",
          "createTime": 1552461622000,
          "creator": null
        }, {
          "id": 42,
          "businessCategory": 1,
          "category": 1,
          "types": 1,
          "channelRO": null,
          "process": 1,
          "name": "666",
          "code": "666",
          "num": "666",
          "subtitle": null,
          "note": "666",
          "problem": "666",
          "repayment": null,
          "repaymentCycle": null,
          "repaymentDay": 13,
          "modelHead": 1,
          "modelYear": 3,
          "overdue": null,
          "defaultRepayment": null,
          "creditLeft": 600,
          "creditRight": 6600,
          "applyLimit": 6,
          "status": 1,
          "basisId": null,
          "description": "666",
          "productCondition": null,
          "productProtocol": null,
          "productRateList": null,
          "productTollList": null,
          "banner": null,
          "productShow": ["政采云云智贷"],
          "updator": 10007000000,
          "updateTime": 1552467403000,
          "smallImage": null,
          "bigImage": null,
          "statistics": null,
          "loop": false,
          "channelName": "中国农业银行股份有限公司浙江省分行",
          "channelId": 1,
          "channelCode": "ABC330106001",
          "createTime": 1552460532000,
          "creator": null
        }, {
          "id": 41,
          "businessCategory": 1,
          "category": 1,
          "types": 1,
          "channelRO": null,
          "process": 1,
          "name": "999",
          "code": "chanpinbianhao01",
          "num": "chanpindaima01",
          "subtitle": null,
          "note": "这是一个999的注意事项",
          "problem": "这是一个999的常见问题",
          "repayment": null,
          "repaymentCycle": null,
          "repaymentDay": 9,
          "modelHead": 1,
          "modelYear": 2,
          "overdue": null,
          "defaultRepayment": null,
          "creditLeft": 900,
          "creditRight": 9900,
          "applyLimit": 9,
          "status": 1,
          "basisId": null,
          "description": "999",
          "productCondition": null,
          "productProtocol": null,
          "productRateList": null,
          "productTollList": null,
          "banner": null,
          "productShow": ["政采云云智贷"],
          "updator": 10007000000,
          "updateTime": 1552467403000,
          "smallImage": null,
          "bigImage": null,
          "statistics": null,
          "loop": true,
          "channelName": "中国农业银行股份有限公司浙江省分行",
          "channelId": 1,
          "channelCode": "ABC330106001",
          "createTime": 1552460458000,
          "creator": null
        }],
        "pageNum": 1,
        "pageSize": 10,
        "pages": 1,
        "size": 3
      },
      "error": null
    });
  },
  '/api/prodPutOn': () => {
    return randomSuccess();
  },
  '/api/prodPutOff': () => {
    return randomSuccess();
  },
};
