const Mock = require('mockjs');

module.exports = {
  '/api/loan/channel/summary/list': () => {
    return Mock.mock([
      {
        error: '测试内容lvxd',
        result: [
          {
            channelCode: '测试内容773u',
            channelName: '测试内容9tl2',
            id: 1,
          },
        ],
        success: true,
      },
    ]);
  },
  '/api/loan/supplier/refundPlans': () => {
    return Mock.mock({
      error: 'xx',
      'result|5-20': [{
        'currentPeriod|+1': 0,
        customerName: 'str',
        loanCode: 'str',
        loanInstitution: 'str',
        productName: 'str',
        repaymentAccount: '测试内容se1j',
        repaymentStatus: 56433,
        restAmount: 0,
        shouldRepaymentInfoRO: {
          date: 'str',
          interest: 0,
          lateCharge: 'str',
          lateFee: 'str',
          penalty: 0,
          principal: 0,
          totalAmount: 0,
        },
        startEndTime: 'str',
      }],
      success: 'true',
    });
  },
  '/api/loan/supplier/refundHistories': () => {
    return Mock.mock({
      error: '错误信息',
      'result|5-20': [{
        customerName: '客户名称',
        loanCode: 'XXXXXX-66666',
        loanInstitution: '中国农业银行',
        period: 10,
        productName: '小微网贷1',
        realRepaymentInfo: {
          account: 200000,
          date: '2019-01-11',
          interest: 200000,
          principal: 200000,
          totalAmount: 200000,
        },
        restAmount: 200000,
        shouldRepaymentInfo: {
          date: '2019-01-11',
          interest: 200000,
          lateCharge: '4.3',
          lateFee: 200000,
          penalty: 200000,
          principal: 200000,
          totalAmount: 200000,
        },
        startEndTime: '2018-12-12至2019-12-11',
        'status|1-6': 1,
      }],
      success: 'true',
    });
  },
  '/api/loan/supplier/repaymentRecords': () => {
    return Mock.mock({
      success: true,
      result: {
        totalAmount: 449000000,
        restAmount: 449000000,
        repaymentPeriod: 1,
        totalPeriod: 12,
        repaymentRecordROList: [
          {
            currentPeriod: 1,
            repaymentStatus: 3,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '2018-08-21',
              interest: 1551669,
              principal: 0,
              totalAmount: 1551669,
            },
            shouldRepaymentInfo: {
              overdueInterest: 0,
              overdueAmount: 0,
              penalty: 0,
              date: '2018-08-21',
              interest: 2483494,
              principal: 0,
              totalAmount: 2483494,
            },
          },
          {
            currentPeriod: 2,
            repaymentStatus: 4,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2018-09-21',
              interest: 2749583,
              principal: 0,
              totalAmount: 2749583,
            },
          },
          {
            currentPeriod: 3,
            repaymentStatus: 4,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2018-10-21',
              interest: 2660887,
              principal: 0,
              totalAmount: 2660887,
            },
          },
          {
            currentPeriod: 4,
            repaymentStatus: 4,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2018-11-21',
              interest: 2749583,
              principal: 0,
              totalAmount: 2749583,
            },
          },
          {
            currentPeriod: 5,
            repaymentStatus: 2,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2018-12-21',
              interest: 2660887,
              principal: 0,
              totalAmount: 2660887,
            },
          },
          {
            currentPeriod: 6,
            repaymentStatus: 2,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2019-01-21',
              interest: 2749583,
              principal: 0,
              totalAmount: 2749583,
            },
          },
          {
            currentPeriod: 7,
            repaymentStatus: 2,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2019-02-21',
              interest: 2749583,
              principal: 0,
              totalAmount: 2749583,
            },
          },
          {
            currentPeriod: 8,
            repaymentStatus: 2,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2019-03-21',
              interest: 2483494,
              principal: 0,
              totalAmount: 2483494,
            },
          },
          {
            currentPeriod: 9,
            repaymentStatus: 2,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2019-04-21',
              interest: 2749583,
              principal: 0,
              totalAmount: 2749583,
            },
          },
          {
            currentPeriod: 10,
            repaymentStatus: 2,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2019-05-21',
              interest: 2660887,
              principal: 0,
              totalAmount: 2660887,
            },
          },
          {
            currentPeriod: 11,
            repaymentStatus: 2,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2019-06-21',
              interest: 2749583,
              principal: 0,
              totalAmount: 2749583,
            },
          },
          {
            currentPeriod: 12,
            repaymentStatus: 2,
            restAmount: null,
            startTime: null,
            endTime: null,
            realRepaymentInfo: {
              account: '中国农业银行兰溪城西支行 19620301040004576',
              date: '',
              interest: null,
              principal: null,
              totalAmount: null,
            },
            shouldRepaymentInfo: {
              overdueInterest: null,
              overdueAmount: null,
              penalty: null,
              date: '2019-07-21',
              interest: 2838279,
              principal: 449000000,
              totalAmount: 451838279,
            },
          },
        ],
      },
      error: null,
    });
  },
  '/api/loan/supplier/loanRecords': () => {
    return Mock.mock({
      success: true,
      result: {
        total: 7,
        data: [{
          id: 23,
          code: '20190307ZJHZGYS4967-2-9843-loanCode',
          contractCode: '20190307ZJHZGYS4967_ht',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          amount: 10000,
          restAmount: 0,
          annualizedRate: 10000,
          totalPeriod: 8,
          restPeriod: 8,
          repaymentMode: 1,
          repaymentDate: 21,
          repaymentAccount: '农行 19000101040001196',
          duration: 2,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 3,
          customerType: '批发代理',
          customerName: '青峰平阳县本级供应商',
          loanTime: '2019-01-15 00:00:00',
        }, {
          id: 24,
          code: '20190307ZJHZGYS4967-2-8859-loanCode',
          contractCode: '20190307ZJHZGYS4967_ht',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          amount: 10000,
          restAmount: 10000,
          annualizedRate: 10000,
          totalPeriod: 3,
          restPeriod: 3,
          repaymentMode: 1,
          repaymentDate: 21,
          repaymentAccount: '农行 19000101040001196',
          duration: 2,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 1,
          customerType: '批发代理',
          customerName: '青峰平阳县本级供应商',
          loanTime: '2019-01-15 00:00:00',
        }, {
          id: 28,
          code: '20190307ZJHZGYS4967-3-9840-loanCode',
          contractCode: '20190307ZJHZGYS4967_ht',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          amount: 10000,
          restAmount: 10000,
          annualizedRate: 10000,
          totalPeriod: 8,
          restPeriod: 2,
          repaymentMode: 1,
          repaymentDate: 21,
          repaymentAccount: '农行 19000101040001196',
          duration: 8,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 1,
          customerType: '生产制造',
          customerName: 'testa',
          loanTime: '2019-01-15 00:00:00',
        }, {
          id: 29,
          code: '20190307ZJHZGYS4967-3-9841-loanCode',
          contractCode: '20190307ZJHZGYS4967_ht',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          amount: 10000,
          restAmount: 10000,
          annualizedRate: 10000,
          totalPeriod: 2,
          restPeriod: 2,
          repaymentMode: 1,
          repaymentDate: 21,
          repaymentAccount: '农行 19000101040001196',
          duration: 2,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 3,
          customerType: '批发代理',
          customerName: 'testa',
          loanTime: '2019-01-15 00:00:00',
        }, {
          id: 30,
          code: '20190307ZJHZGYS4967-3-9842-loanCode',
          contractCode: '20190307ZJHZGYS4967_ht',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          amount: 10000,
          restAmount: 10000,
          annualizedRate: 10000,
          totalPeriod: 2,
          restPeriod: 2,
          repaymentMode: 1,
          repaymentDate: 21,
          repaymentAccount: '农行 19000101040001196',
          duration: 2,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 4,
          customerType: '批发代理',
          customerName: 'testa',
          loanTime: '2019-01-15 00:00:00',
        }, {
          id: 31,
          code: '20190307ZJHZGYS4967-3-9843-loanCode',
          contractCode: ' 20190307ZJHZGYS4967_ht',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          amount: 10000,
          restAmount: 10000,
          annualizedRate: 10000,
          totalPeriod: 8,
          restPeriod: 2,
          repaymentMode: 1,
          repaymentDate: 21,
          repaymentAccount: '农行 19000101040001196',
          duration: 8,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 3,
          customerType: '生产制造',
          customerName: 'testa',
          loanTime: '2019-01-15 00:00:00',
        }, {
          id: 32,
          code: '20190307ZJHZGYS4967-3-9844-loanCode',
          contractCode: '20190307ZJHZGYS4967_ht',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          amount: 10000,
          restAmount: 10000,
          annualizedRate: 10000,
          totalPeriod: 2,
          restPeriod: 2,
          repaymentMode: 1,
          repaymentDate: 21,
          repaymentAccount: '农行 19000101040001196',
          duration: 2,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 4,
          customerType: '批发代理',
          customerName: 'testa',
          loanTime: '2019-01-15 00:00:00',
        }],
        pageNum: 1,
        pageSize: 10,
        pages: 1,
        size: 7,
      },
      error: null,
    });
  },

  '/api/loan/supplier/repaymentHistories': () => {
    return Mock.mock({
      success: true,
      result: {
        total: 11,
        data: [{
          id: 35,
          loanCode: '20190307ZJHZGYS4967-2-9843-loanCode',
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          period: 1,
          restAmount: 0,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 3,
          deductionType: 1,
          realRepaymentInfo: {
            account: ' ',
            date: '2019-01-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
          shouldRepaymentInfo: {
            overdueInterest: 0,
            overdueAmount: 0,
            penalty: 0,
            date: '2019-01-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }, {
          id: 36,
          loanCode: '20190307ZJHZGYS4967-2-9843-loanCode',
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          period: 2,
          restAmount: 0,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 3,
          deductionType: 1,
          realRepaymentInfo: {
            account: ' ',
            date: '2019-02-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
          shouldRepaymentInfo: {
            overdueInterest: 0,
            overdueAmount: 0,
            penalty: 0,
            date: '2019-02-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }, {
          id: 37,
          loanCode: '20190307ZJHZGYS4967-2-9843-loanCode',
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          period: 3,
          restAmount: 0,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 3,
          deductionType: 1,
          realRepaymentInfo: {
            account: ' ',
            date: '2019-03-21',
            interest: 10,
            principal: 0,
            totalAmount: 10,
          },
          shouldRepaymentInfo: {
            overdueInterest: 0,
            overdueAmount: 0,
            penalty: 0,
            date: '2019-03-21',
            interest: 10,
            principal: 0,
            totalAmount: 10,
          },
        }, {
          id: 48,
          loanCode: '20190307ZJHZGYS4967-3-9840-loanCode',
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          period: 1,
          restAmount: 0,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 3,
          deductionType: 1,
          realRepaymentInfo: {
            account: ' ',
            date: '2018-12-21',
            interest: 7,
            principal: 0,
            totalAmount: 7,
          },
          shouldRepaymentInfo: {
            overdueInterest: 0,
            overdueAmount: 0,
            penalty: 0,
            date: '2018-12-21',
            interest: 7,
            principal: 0,
            totalAmount: 7,
          },
        }, {
          id: 49,
          loanCode: '20190307ZJHZGYS4967-3-9840-loanCode',
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          period: 2,
          restAmount: 0,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 5,
          deductionType: 1,
          realRepaymentInfo: {
            account: ' ',
            date: '2019-01-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
          shouldRepaymentInfo: {
            overdueInterest: 10000,
            overdueAmount: 5,
            penalty: 5,
            date: '2019-01-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }, {
          id: 50,
          loanCode: '20190307ZJHZGYS4967-3-9840-loanCode',
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          period: 3,
          restAmount: 0,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 5,
          deductionType: 1,
          realRepaymentInfo: {
            account: ' ',
            date: '2019-02-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
          shouldRepaymentInfo: {
            overdueInterest: 10000,
            overdueAmount: 5,
            penalty: 5,
            date: '2019-02-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }, {
          id: 51,
          loanCode: '20190307ZJHZGYS4967-3-9840-loanCode',
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          period: 4,
          restAmount: 0,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 6,
          deductionType: 1,
          realRepaymentInfo: {
            account: ' ',
            date: '2019-02-21',
            interest: 9,
            principal: 10000,
            totalAmount: 10009,
          },
          shouldRepaymentInfo: {
            overdueInterest: 0,
            overdueAmount: 0,
            penalty: 0,
            date: '2019-02-21',
            interest: 9,
            principal: 10000,
            totalAmount: 10009,
          },
        }, {
          id: 61,
          loanCode: '20190307ZJHZGYS4967-3-9841-loanCode',
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          period: 1,
          restAmount: 0,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 3,
          deductionType: 1,
          realRepaymentInfo: {
            account: ' ',
            date: '2018-12-21',
            interest: 7,
            principal: 0,
            totalAmount: 7,
          },
          shouldRepaymentInfo: {
            overdueInterest: 0,
            overdueAmount: 0,
            penalty: 0,
            date: '2018-12-21',
            interest: 7,
            principal: 0,
            totalAmount: 7,
          },
        }, {
          id: 62,
          loanCode: '20190307ZJHZGYS4967-3-9841-loanCode',
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          period: 2,
          restAmount: 0,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 5,
          deductionType: 1,
          realRepaymentInfo: {
            account: ' ',
            date: '2019-01-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
          shouldRepaymentInfo: {
            overdueInterest: 10000,
            overdueAmount: 5,
            penalty: 5,
            date: '2019-01-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }, {
          id: 63,
          loanCode: '20190307ZJHZGYS4967-3-9841-loanCode',
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          period: 3,
          restAmount: 0,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          status: 5,
          deductionType: 1,
          realRepaymentInfo: {
            account: ' ',
            date: '2019-02-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
          shouldRepaymentInfo: {
            overdueInterest: 10000,
            overdueAmount: 5,
            penalty: 5,
            date: '2019-02-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }],
        pageNum: 1,
        pageSize: 10,
        pages: 2,
        size: 10,
      },
      error: null,
    });
  },

  '/api/loan/supplier/repaymentPlans': () => {
    return Mock.mock({
      success: true,
      result: {
        total: 8,
        data: [{
          id: 38,
          loanCode: '20190307ZJHZGYS4967-2-8859-loanCode',
          currentPeriod: 1,
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          restAmount: 10000,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          repaymentAccount: '农行 19000101040001196',
          repaymentStatus: 1,
          shouldRepaymentInfo: {
            overdueInterest: null,
            overdueAmount: null,
            penalty: null,
            date: '2019-01-21',
            interest: 2,
            principal: 0,
            totalAmount: 2,
          },
        }, {
          id: 39,
          loanCode: '20190307ZJHZGYS4967-2-8859-loanCode',
          currentPeriod: 2,
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          restAmount: 10000,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          repaymentAccount: '农行 19000101040001196',
          repaymentStatus: 2,
          shouldRepaymentInfo: {
            overdueInterest: null,
            overdueAmount: null,
            penalty: null,
            date: '2019-02-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }, {
          id: 40,
          loanCode: '20190307ZJHZGYS4967-2-8859-loanCode',
          currentPeriod: 3,
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          restAmount: 10000,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          repaymentAccount: '农行 19000101040001196',
          repaymentStatus: 2,
          shouldRepaymentInfo: {
            overdueInterest: null,
            overdueAmount: null,
            penalty: null,
            date: '2019-03-21',
            interest: 10,
            principal: 0,
            totalAmount: 10,
          },
        }, {
          id: 52,
          loanCode: '20190307ZJHZGYS4967-3-9840-loanCode',
          currentPeriod: 5,
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          restAmount: 10000,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          repaymentAccount: '农行 19000101040001196',
          repaymentStatus: 2,
          shouldRepaymentInfo: {
            overdueInterest: null,
            overdueAmount: null,
            penalty: null,
            date: '2019-04-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }, {
          id: 53,
          loanCode: '20190307ZJHZGYS4967-3-9840-loanCode',
          currentPeriod: 6,
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          restAmount: 10000,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          repaymentAccount: '农行 19000101040001196',
          repaymentStatus: 7,
          shouldRepaymentInfo: {
            overdueInterest: null,
            overdueAmount: null,
            penalty: null,
            date: '2019-05-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }, {
          id: 54,
          loanCode: '20190307ZJHZGYS4967-3-9840-loanCode',
          currentPeriod: 7,
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          restAmount: 10000,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          repaymentAccount: '农行 19000101040001196',
          repaymentStatus: 7,
          shouldRepaymentInfo: {
            overdueInterest: null,
            overdueAmount: null,
            penalty: null,
            date: '2019-06-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }, {
          id: 65,
          loanCode: '20190307ZJHZGYS4967-3-9841-loanCode',
          currentPeriod: 5,
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          restAmount: 10000,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          repaymentAccount: '农行 19000101040001196',
          repaymentStatus: 2,
          shouldRepaymentInfo: {
            overdueInterest: null,
            overdueAmount: null,
            penalty: null,
            date: '2019-04-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }, {
          id: 66,
          loanCode: '20190307ZJHZGYS4967-3-9841-loanCode',
          currentPeriod: 6,
          customerName: 'testa',
          loanInstitution: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          restAmount: 10000,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          repaymentAccount: '农行 19000101040001196',
          repaymentStatus: 7,
          shouldRepaymentInfo: {
            overdueInterest: null,
            overdueAmount: null,
            penalty: null,
            date: '2019-05-21',
            interest: 9,
            principal: 0,
            totalAmount: 9,
          },
        }],
        pageNum: 1,
        pageSize: 10,
        pages: 1,
        size: 8,
      },
      error: null,
    });
  },

  '/api/loan/supplier/quotaRecords': () => {
    return Mock.mock({
      success: true,
      result: {
        total: 3,
        data: [{
          id: 26,
          contractCode: '20190307ZJHZGYS4967_ht',
          customerName: 'test1120a',
          creditInstitution: '中国农业银行股份有限公司浙江省分行',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          quotaType: 1,
          annualizedRate: 10000,
          quota: 10000,
          availableQuota: 19700,
          duration: 2,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          rateType: 1,
          floatRate: 0,
          status: 1,
        }, {
          id: 27,
          contractCode: '20190307ZJHZGYS4967_ht',
          customerName: 'test1120a',
          creditInstitution: '中国农业银行股份有限公司浙江省分行',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          quotaType: 1,
          annualizedRate: 10000,
          quota: 10000,
          availableQuota: 19700,
          duration: 2,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          rateType: 1,
          floatRate: 0,
          status: 1,
        }, {
          id: 28,
          contractCode: '20190307ZJHZGYS4967_ht',
          customerName: 'test1120a',
          creditInstitution: '中国农业银行股份有限公司浙江省分行',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷1号',
          quotaType: 1,
          annualizedRate: 10000,
          quota: 10000,
          availableQuota: 19700,
          duration: 2,
          startTime: '2019-01-15',
          endTime: '2019-03-28',
          rateType: 1,
          floatRate: 0,
          status: 2,
        }],
        pageNum: 1,
        pageSize: 10,
        pages: 1,
        size: 3,
      },
      error: null,
    });
  },
  '/api/loan/supplier/applyRecords': () => {
    return Mock.mock({
      success: true,
      result: {
        total: 2,
        data: [{
          id: 52,
          customerId: 1000100024711,
          applyCode: '20190313ZJWZQFPYXBJGYS9634-1',
          applicant: null,
          onlineInitiator: '楼方',
          applyTime: '',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '流水贷',
          productCategory: null,
          productType: null,
          applyAmount: null,
          approveAmount: null,
          annualizedRate: null,
          approveTime: null,
          customerApplyStatus: 1,
          contractCode: null,
        }, {
          id: 53,
          customerId: 1000100024711,
          applyCode: '20190313ZJWZQFPYXBJGYS9634-2-1156',
          applicant: '测试申请贷款人1',
          onlineInitiator: '楼方',
          applyTime: '2019-03-11 10:12:38',
          capitalChannel: '中国农业银行股份有限公司浙江省分行',
          productName: '合同贷',
          productCategory: null,
          productType: null,
          applyAmount: 20000,
          approveAmount: null,
          annualizedRate: null,
          approveTime: null,
          customerApplyStatus: 1,
          contractCode: null,
        }],
        pageNum: 1,
        pageSize: 10,
        pages: 1,
        size: 2,
      },
      error: null,
    });
  },
  '/api/loan/account/info': () => {
    return Mock.mock({
      success: true,
      result: {
        accountInfo: {
          userName: '青峰平阳县本级供应商111111',
          avatar: null,
          integrityScore: 590,
          lastDueDate: null,
          monthShouldReturn: null,
          totalBorrow: 0,
          totalRepayment: 0,
          totalToPay: 0,
        },
        userLoanInfo: [{
          "applicationStatus": 0,
          "capitalChannel": "中国农业银行股份有限公司浙江省分行",
          "productName": "青峰平阳县本级供应商2019年03月13日(1)",
          "loanAmount": 0,
          "availableQuota": 10000
        },],
        'recommendInfo|3': [{
          id: /^\d{6,10}$/,
          smallImage: '@img',
        }],
      },
      error: null,
    })
  },
  '/help-center/api/cmsProductDynamics/getProductDynamicsContentsByCode': () => {
    return [{
      id: 2721,
      siteId: 2,
      title: '2019年3月15日供应商页面优化一期',
      userId: 8,
      checkUserId: 8,
      categoryId: 120,
      modelId: 10,
      parentId: null,
      copied: false,
      author: null,
      editor: '',
      onlyUrl: false,
      hasImages: false,
      hasFiles: false,
      hasStatic: true,
      url: '//help.test.zcygov.cn/web/site_2/2019/03/13/2721.html',
      description: '',
      tagIds: '',
      cover: null,
      childs: 0,
      scores: 0,
      comments: 0,
      clicks: 0,
      publishDate: 1552461178000,
      createDate: 1552461178000,
      status: 1,
      disabled: false,
    }, {
      id: 2717,
      siteId: 2,
      title: '2019年3月14日疫苗馆更新',
      userId: 8,
      checkUserId: 8,
      categoryId: 195,
      modelId: 10,
      parentId: null,
      copied: false,
      author: null,
      editor: '',
      onlyUrl: false,
      hasImages: false,
      hasFiles: false,
      hasStatic: true,
      url: '//help.test.zcygov.cn/web/site_2/2019/03/12/2717.html',
      description: '',
      tagIds: '',
      cover: null,
      childs: 0,
      scores: 0,
      comments: 0,
      clicks: 0,
      publishDate: 1552385469000,
      createDate: 1552385469000,
      status: 1,
      disabled: false,
    }, {
      id: 2716,
      siteId: 2,
      title: '2019年3月14日专家库更新',
      userId: 8,
      checkUserId: 8,
      categoryId: 199,
      modelId: 10,
      parentId: null,
      copied: false,
      author: null,
      editor: '',
      onlyUrl: false,
      hasImages: false,
      hasFiles: false,
      hasStatic: true,
      url: '//help.test.zcygov.cn/web/site_2/2019/03/12/2716.html',
      description: '',
      tagIds: '',
      cover: null,
      childs: 0,
      scores: 0,
      comments: 0,
      clicks: 0,
      publishDate: 1552385238000,
      createDate: 1552385238000,
      status: 1,
      disabled: false,
    }, {
      id: 2715,
      siteId: 2,
      title: '2019年3月14日项目采购更新',
      userId: 8,
      checkUserId: 8,
      categoryId: 201,
      modelId: 10,
      parentId: null,
      copied: false,
      author: null,
      editor: '',
      onlyUrl: false,
      hasImages: false,
      hasFiles: false,
      hasStatic: true,
      url: '//help.test.zcygov.cn/web/site_2/2019/03/12/2715.html',
      description: '',
      tagIds: '',
      cover: null,
      childs: 0,
      scores: 0,
      comments: 0,
      clicks: 0,
      publishDate: 1552385119000,
      createDate: 1552385119000,
      status: 1,
      disabled: false,
    }, {
      id: 2714,
      siteId: 2,
      title: '2019年3月13日通用定点更新',
      userId: 8,
      checkUserId: 8,
      categoryId: 248,
      modelId: 10,
      parentId: null,
      copied: false,
      author: null,
      editor: '',
      onlyUrl: false,
      hasImages: false,
      hasFiles: false,
      hasStatic: true,
      url: '//help.test.zcygov.cn/web/site_2/2019/03/11/2714.html',
      description: '',
      tagIds: '',
      cover: null,
      childs: 0,
      scores: 0,
      comments: 0,
      clicks: 0,
      publishDate: 1552297047000,
      createDate: 1552297047000,
      status: 1,
      disabled: false,
    }, {
      id: 2713,
      siteId: 2,
      title: '2019年3月12日采购计划更新',
      userId: 8,
      checkUserId: 8,
      categoryId: 184,
      modelId: 10,
      parentId: null,
      copied: false,
      author: null,
      editor: '',
      onlyUrl: false,
      hasImages: false,
      hasFiles: false,
      hasStatic: true,
      url: '//help.test.zcygov.cn/web/site_2/2019/03/11/2713.html',
      description: '',
      tagIds: '',
      cover: null,
      childs: 0,
      scores: 0,
      comments: 0,
      clicks: 0,
      publishDate: 1552285116000,
      createDate: 1552285116000,
      status: 1,
      disabled: false,
    }, {
      id: 2710,
      siteId: 2,
      title: '2019年3月7日疫苗馆更新',
      userId: 8,
      checkUserId: 8,
      categoryId: 192,
      modelId: 10,
      parentId: null,
      copied: false,
      author: null,
      editor: '',
      onlyUrl: false,
      hasImages: false,
      hasFiles: false,
      hasStatic: true,
      url: '//help.test.zcygov.cn/web/site_2/2019/03/06/2710.html',
      description: '',
      tagIds: '',
      cover: null,
      childs: 0,
      scores: 0,
      comments: 0,
      clicks: 0,
      publishDate: 1551858624000,
      createDate: 1551858624000,
      status: 1,
      disabled: false,
    }, {
      id: 2709,
      siteId: 2,
      title: '19年3月7日项目采购、疫苗馆更新',
      userId: 8,
      checkUserId: 8,
      categoryId: 315,
      modelId: 10,
      parentId: null,
      copied: false,
      author: null,
      editor: '',
      onlyUrl: false,
      hasImages: false,
      hasFiles: false,
      hasStatic: true,
      url: '//help.test.zcygov.cn/web/site_2/2019/03/06/2709.html',
      description: '',
      tagIds: '',
      cover: null,
      childs: 0,
      scores: 0,
      comments: 0,
      clicks: 0,
      publishDate: 1551857803000,
      createDate: 1551857803000,
      status: 1,
      disabled: false,
    }, {
      id: 2708,
      siteId: 2,
      title: '19年3月5日教育装备、网上超市更新',
      userId: 8,
      checkUserId: 8,
      categoryId: 315,
      modelId: 10,
      parentId: null,
      copied: false,
      author: null,
      editor: '',
      onlyUrl: false,
      hasImages: false,
      hasFiles: false,
      hasStatic: true,
      url: '//help.test.zcygov.cn/web/site_2/2019/03/06/2708.html',
      description: '',
      tagIds: '',
      cover: null,
      childs: 0,
      scores: 0,
      comments: 0,
      clicks: 0,
      publishDate: 1551857697000,
      createDate: 1551857697000,
      status: 1,
      disabled: false,
    }, {
      id: 2705,
      siteId: 2,
      title: '2019年3月5日网上超市更新',
      userId: 8,
      checkUserId: 8,
      categoryId: 123,
      modelId: 10,
      parentId: null,
      copied: false,
      author: null,
      editor: '',
      onlyUrl: false,
      hasImages: false,
      hasFiles: false,
      hasStatic: true,
      url: '//help.test.zcygov.cn/web/site_2/2019/03/04/2705.html',
      description: '',
      tagIds: '',
      cover: null,
      childs: 0,
      scores: 0,
      comments: 0,
      clicks: 0,
      publishDate: 1551692486000,
      createDate: 1551692486000,
      status: 1,
      disabled: false,
    }];
  },

};
